### ISSUE TITLE
Install on Debian

### ISSUE THREAD

**Issue by cvetanet** [Minda1975/i3wm-in-Debian-9#1]
Please tell me how to install your config on debian 9.8 system.
Good work!

**Comment by Minda1975** [comment]
> Please tell me how to install your config on debian 9.8 system.

Hello. It is very simple. In Debian system, you need install these programs: `i3,  rxvt-unicode-256color, conky-all, dunst, rofi, suckless-tools, scrot, imagemagick, feh, viewnior`. These are necessary programs. If you like mpd music daemon, install `mpd, mpc and ncmpcpp`. Configure the music daemon according to your system. Then, clone the repository, move folder `.fonts` (essential!) to home directory. Same goes to folders `.scripts, .utility, .xrdb` and files  `.conkyrc` and `.conkyi3`. To `.config` directory, move folders `dunst,  rofi-power, mpd` and `ncmpcpp`. Configure the ncmpcpp config and scripts in this folder according to your system. Then, check my i3wm config, change your i3 config file to my file. Logout and log back. 

P.S.

Also i included scripts for capturing videos of your dektop (in .utility folder). So you don't need any external program. You just need ffmpeg and mkv codec, mostly autoinstalled when You have a multimedia player like Smplayer. To use this, just launch the script record. The video will be saved in ~/Videos/record.mkv. Rename it first before take another recording session 😆

 To stop recording, just navigate to script stop-recording and launch it.

If you are experiencing difficulties or problems in the future, ask.

**Comment by Minda1975** [comment]
Since there is no feedback from the bugr submitter, I close this issue. If you are uncertain, you can create a new issue.
